<?php

namespace Database\Seeders;

use App\Models\Doctor;
use Illuminate\Database\Seeder;

class DoctorSeeder extends Seeder
{
    public function run(): void
    {
        Doctor::unguard();

        $doctors = [
            [
                'first_name'              => 'Ahmad',
                'middle_name'             => 'Ali',
                'last_name'               => 'Khan',
                'date_of_birth'           => '1975-03-15',
                'gender'                  => 'male',
                'address'                 => '123 Central Park West',
                'city'                    => 'New York',
                'state'                   => 'NY',
                'zip_code'                => '10001',
                'email'                   => 'ahmad.khan@hospital.com',
                'phone'                   => '+12340001',
                'emergency_contact_name'  => 'Fatima Khan',
                'emergency_contact_phone' => '+12349991',
                'license_number'          => 'MD-NY-784512',
                'license_expiry_date'     => '2028-12-31',
                'qualifications'          => 'MD, FCPS (Cardiology)',
                'years_experience'        => 18,
                'education'               => 'Aga Khan University (MBBS), Royal College of Physicians (FCPS)',
                'certifications'          => 'ACLS, BLS, Interventional Cardiology Fellowship',
                'position'                => 'Senior Consultant Cardiologist',
                'hourly_rate'             => 350.00,
                'department_id'           => 1,
                'primary_specialization_id' => 1,
                'profile_photo'           => null,
                'is_active'               => true,
            ],
            [
                'first_name'              => 'Sarah',
                'middle_name'             => null,
                'last_name'               => 'Williams',
                'date_of_birth'           => '1983-07-22',
                'gender'                  => 'female',
                'address'                 => '456 Beacon Street',
                'city'                    => 'Boston',
                'state'                   => 'MA',
                'zip_code'                => '02101',
                'email'                   => 'sarah.williams@hospital.com',
                'phone'                   => '+12340002',
                'emergency_contact_name'  => 'David Williams',
                'emergency_contact_phone' => '+12349992',
                'license_number'          => 'MD-MA-892347',
                'license_expiry_date'     => '2029-06-30',
                'qualifications'          => 'MD, Fellowship in Pediatric Cardiology',
                'years_experience'        => 10,
                'education'               => 'Harvard Medical School',
                'certifications'          => 'Board Certified in Pediatric Cardiology',
                'position'                => 'Consultant Pediatric Cardiologist',
                'hourly_rate'             => 280.00,
                'department_id'           => 1,
                'primary_specialization_id' => 3,
                'profile_photo'           => null,
                'is_active'               => true,
            ],
            [
                'first_name'              => 'Michael',
                'middle_name'             => 'James',
                'last_name'               => 'Brown',
                'date_of_birth'           => '1971-11-08',
                'gender'                  => 'male',
                'address'                 => '789 Michigan Avenue',
                'city'                    => 'Chicago',
                'state'                   => 'IL',
                'zip_code'                => '60601',
                'email'                   => 'michael.brown@hospital.com',
                'phone'                   => '+12340003',
                'emergency_contact_name'  => 'Linda Brown',
                'emergency_contact_phone' => '+12349993',
                'license_number'          => 'MD-IL-561289',
                'license_expiry_date'     => '2030-03-15',
                'qualifications'          => 'MD, DM (Neurology), FRCP',
                'years_experience'        => 22,
                'education'               => 'University of Chicago Pritzker School of Medicine',
                'certifications'          => 'Stroke Specialist, Neurocritical Care',
                'position'                => 'Head of Neurology',
                'hourly_rate'             => 420.00,
                'department_id'           => 2,
                'primary_specialization_id' => 4,
                'profile_photo'           => null,
                'is_active'               => true,
            ],
            [
                'first_name'              => 'Priya',
                'middle_name'             => null,
                'last_name'               => 'Patel',
                'date_of_birth'           => '1979-02-28',
                'gender'                  => 'female',
                'address'                 => '321 Sunset Boulevard',
                'city'                    => 'Los Angeles',
                'state'                   => 'CA',
                'zip_code'                => '90001',
                'email'                   => 'priya.patel@hospital.com',
                'phone'                   => '+12340004',
                'emergency_contact_name'  => 'Rajesh Patel',
                'emergency_contact_phone' => '+12349994',
                'license_number'          => 'MD-CA-673921',
                'license_expiry_date'     => '2028-09-30',
                'qualifications'          => 'MBBS, MS (Orthopedics), Fellowship in Joint Replacement',
                'years_experience'        => 16,
                'education'               => 'UCLA Medical School, AIIMS Delhi',
                'certifications'          => 'AO Trauma, Joint Replacement Surgery',
                'position'                => 'Senior Orthopedic Surgeon',
                'hourly_rate'             => 390.00,
                'department_id'           => 3,
                'primary_specialization_id' => 6,
                'profile_photo'           => null,
                'is_active'               => true,
            ],
            [
                'first_name'              => 'Omar',
                'middle_name'             => 'Hassan',
                'last_name'               => 'Farooq',
                'date_of_birth'           => '1982-09-12',
                'gender'                  => 'male',
                'address'                 => '555 Medical Center Drive',
                'city'                    => 'Houston',
                'state'                   => 'TX',
                'zip_code'                => '77001',
                'email'                   => 'omar.farooq@hospital.com',
                'phone'                   => '+12340005',
                'emergency_contact_name'  => 'Aisha Farooq',
                'emergency_contact_phone' => '+12349995',
                'license_number'          => 'MD-TX-448721',
                'license_expiry_date'     => '2029-11-01',
                'qualifications'          => 'MD, Fellowship in Neonatology',
                'years_experience'        => 13,
                'education'               => 'Baylor College of Medicine',
                'certifications'          => 'Neonatal Resuscitation Program Instructor',
                'position'                => 'Neonatologist',
                'hourly_rate'             => 310.00,
                'department_id'           => 4,
                'primary_specialization_id' => 9,
                'profile_photo'           => null,
                'is_active'               => true,
            ],
            [
    'first_name'              => 'Fatima',
    'middle_name'             => 'Zahra',
    'last_name'               => 'Ahmed',
    'date_of_birth'           => '1981-06-20',
    'gender'                  => 'female',
    'address'                 => '88 Kings Road',
    'city'                    => 'London',
    'state'                   => 'NY',
    'zip_code'                => '10019',
    'email'                   => 'fatima.ahmed@hospital.com',
    'phone'                   => '+12340006',
    'emergency_contact_name'  => 'Mohammed Ahmed',
    'emergency_contact_phone' => '+12349996',
    'license_number'          => 'MD-NY-129834',
    'license_expiry_date'     => '2030-05-31',
    'qualifications'          => 'MD, Fellowship in Electrophysiology',
    'years_experience'        => 14,
    'education'               => 'Johns Hopkins University',
    'certifications'          => 'Certified Cardiac Electrophysiologist',
    'position'                => 'Cardiac Electrophysiologist',
    'hourly_rate'             => 380.00,
    'department_id'           => 1,        // Cardiology
    'primary_specialization_id' => 1,      // Interventional Cardiology (still valid subspecialty)
    'profile_photo'           => null,
    'is_active'               => true,
],
[
    'first_name'              => 'James',
    'middle_name'             => 'Robert',
    'last_name'               => 'Wilson',
    'date_of_birth'           => '1977-09-14',
    'gender'                  => 'male',
    'address'                 => '450 Park Avenue',
    'city'                    => 'New York',
    'state'                   => 'NY',
    'zip_code'                => '10022',
    'email'                   => 'james.wilson@hospital.com',
    'phone'                   => '+12340007',
    'emergency_contact_name'  => 'Emma Wilson',
    'emergency_contact_phone' => '+12349997',
    'license_number'          => 'MD-NY-447821',
    'license_expiry_date'     => '2029-08-15',
    'qualifications'          => 'MD, DM (Neurology)',
    'years_experience'        => 18,
    'education'               => 'Columbia University',
    'certifications'          => 'Board Certified in Epilepsy',
    'position'                => 'Epileptologist',
    'hourly_rate'             => 360.00,
    'department_id'           => 2,        // Neurology
    'primary_specialization_id' => 5,      // Epilepsy & Seizure Disorders
    'profile_photo'           => null,
    'is_active'               => true,
],
[
    'first_name'              => 'Anita',
    'middle_name'             => null,
    'last_name'               => 'Sharma',
    'date_of_birth'           => '1984-03-11',
    'gender'                  => 'female',
    'address'                 => '77 Massachusetts Ave',
    'city'                    => 'Boston',
    'state'                   => 'MA',
    'zip_code'                => '02139',
    'email'                   => 'anita.sharma@hospital.com',
    'phone'                   => '+12340008',
    'emergency_contact_name'  => 'Vikram Sharma',
    'emergency_contact_phone' => '+12349998',
    'license_number'          => 'MD-MA-773291',
    'license_expiry_date'     => '2031-02-28',
    'qualifications'          => 'MBBS, DNB Ortho, Fellowship in Sports Medicine',
    'years_experience'        => 12,
    'education'               => 'AIIMS New Delhi, Harvard',
    'certifications'          => 'FAANA, Arthroscopy Specialist',
    'position'                => 'Sports Medicine & Arthroscopy Surgeon',
    'hourly_rate'             => 340.00,
    'department_id'           => 3,        // Orthopedics
    'primary_specialization_id' => 7,      // Sports Medicine
    'profile_photo'           => null,
    'is_active'               => true,
],
[
    'first_name'              => 'Carlos',
    'middle_name'             => 'Miguel',
    'last_name'               => 'Ramirez',
    'date_of_birth'           => '1980-12-05',
    'gender'                  => 'male',
    'address'                 => '123 Palm Street',
    'city'                    => 'Miami',
    'state'                   => 'FL',
    'zip_code'                => '33130',
    'email'                   => 'carlos.ramirez@hospital.com',
    'phone'                   => '+12340009',
    'emergency_contact_name'  => 'Sofia Ramirez',
    'emergency_contact_phone' => '+12349999',
    'license_number'          => 'MD-FL-338912',
    'license_expiry_date'     => '2028-10-30',
    'qualifications'          => 'MD, FAAP',
    'years_experience'        => 15,
    'education'               => 'University of Miami',
    'certifications'          => 'Board Certified in General Pediatrics',
    'position'                => 'Senior Pediatrician',
    'hourly_rate'             => 260.00,
    'department_id'           => 4,        // Pediatrics
    'primary_specialization_id' => 8,      // General Pediatrics
    'profile_photo'           => null,
    'is_active'               => true,
],
[
    'first_name'              => 'Laura',
    'middle_name'             => 'Elizabeth',
    'last_name'               => 'Miller',
    'date_of_birth'           => '1979-07-19',
    'gender'                  => 'female',
    'address'                 => '200 Medical Plaza',
    'city'                    => 'Los Angeles',
    'state'                   => 'CA',
    'zip_code'                => '90095',
    'email'                   => 'laura.miller@hospital.com',
    'phone'                   => '+12340010',
    'emergency_contact_name'  => 'Thomas Miller',
    'emergency_contact_phone' => '+12349990',
    'license_number'          => 'MD-CA-556789',
    'license_expiry_date'     => '2030-07-01',
    'qualifications'          => 'MD, Hematology/Oncology Fellowship',
    'years_experience'        => 17,
    'education'               => 'UCLA David Geffen School of Medicine',
    'certifications'          => 'Board Certified Medical Oncology',
    'position'                => 'Medical Oncologist',
    'hourly_rate'             => 440.00,
    'department_id'           => 5,        // Oncology
    'primary_specialization_id' => 10,     // Medical Oncology
    'profile_photo'           => null,
    'is_active'               => true,
],
[
    'first_name'              => 'Hassan',
    'middle_name'             => null,
    'last_name'               => 'Malik',
    'date_of_birth'           => '1983-01-27',
    'gender'                  => 'male',
    'address'                 => '555 Post Street',
    'city'                    => 'San Francisco',
    'state'                   => 'CA',
    'zip_code'                => '94102',
    'email'                   => 'hassan.malik@hospital.com',
    'phone'                   => '+12340011',
    'emergency_contact_name'  => 'Noor Malik',
    'emergency_contact_phone' => '+12349989',
    'license_number'          => 'MD-CA-771234',
    'license_expiry_date'     => '2029-11-30',
    'qualifications'          => 'MD, Interventional Cardiology Fellowship',
    'years_experience'        => 13,
    'education'               => 'Stanford University',
    'certifications'          => 'FSCAI',
    'position'                => 'Interventional Cardiologist',
    'hourly_rate'             => 400.00,
    'department_id'           => 1,
    'primary_specialization_id' => 1,
    'profile_photo'           => null,
    'is_active'               => true,
],
[
    'first_name'              => 'Emily',
    'middle_name'             => 'Rose',
    'last_name'               => 'Davis',
    'date_of_birth'           => '1986-04-08',
    'gender'                  => 'female',
    'address'                 => '100 Memorial Drive',
    'city'                    => 'Boston',
    'state'                   => 'MA',
    'zip_code'                => '02142',
    'email'                   => 'emily.davis@hospital.com',
    'phone'                   => '+12340012',
    'emergency_contact_name'  => 'Michael Davis',
    'emergency_contact_phone' => '+12349988',
    'license_number'          => 'MD-MA-882345',
    'license_expiry_date'     => '2031-03-15',
    'qualifications'          => 'MD, Pediatric Neurology Fellowship',
    'years_experience'        => 10,
    'education'               => 'Boston Children’s Hospital / Harvard',
    'certifications'          => 'Child Neurology Specialist',
    'position'                => 'Pediatric Neurologist',
    'hourly_rate'             => 350.00,
    'department_id'           => 2,
    'primary_specialization_id' => 4,      // Stroke Neurology (also valid for peds)
    'profile_photo'           => null,
    'is_active'               => true,
],
[
    'first_name'              => 'Ravi',
    'middle_name'             => null,
    'last_name'               => 'Kumar',
    'date_of_birth'           => '1978-10-30',
    'gender'                  => 'male',
    'address'                 => '789 Ortho Lane',
    'city'                    => 'Chicago',
    'state'                   => 'IL',
    'zip_code'                => '60611',
    'email'                   => 'ravi.kumar@hospital.com',
    'phone'                   => '+12340013',
    'emergency_contact_name'  => 'Sunita Kumar',
    'emergency_contact_phone' => '+12349987',
    'license_number'          => 'MD-IL-119933',
    'license_expiry_date'     => '2028-12-31',
    'qualifications'          => 'MS Ortho, Fellowship in Joint Replacement',
    'years_experience'        => 19,
    'education'               => 'Northwestern University',
    'certifications'          => 'Robotic Joint Replacement Certified',
    'position'                => 'Chief of Joint Replacement',
    'hourly_rate'             => 420.00,
    'department_id'           => 3,
    'primary_specialization_id' => 6,      // Joint Replacement Surgery
    'profile_photo'           => null,
    'is_active'               => true,
],
[
    'first_name'              => 'Sophie',
    'middle_name'             => 'Marie',
    'last_name'               => 'Lefèvre',
    'date_of_birth'           => '1985-05-17',
    'gender'                  => 'female',
    'address'                 => '321 NICU Wing',
    'city'                    => 'Houston',
    'state'                   => 'TX',
    'zip_code'                => '77030',
    'email'                   => 'sophie.lefevre@hospital.com',
    'phone'                   => '+12340014',
    'emergency_contact_name'  => 'Pierre Lefèvre',
    'emergency_contact_phone' => '+12349986',
    'license_number'          => 'MD-TX-667788',
    'license_expiry_date'     => '2030-06-30',
    'qualifications'          => 'MD, Neonatal-Perinatal Fellowship',
    'years_experience'        => 11,
    'education'               => 'Baylor College of Medicine',
    'certifications'          => 'NNP Board Certified',
    'position'                => 'Attending Neonatologist',
    'hourly_rate'             => 330.00,
    'department_id'           => 4,
    'primary_specialization_id' => 9,      // Neonatology
    'profile_photo'           => null,
    'is_active'               => true,
],
[
    'first_name'              => 'Alexander',
    'middle_name'             => 'Paul',
    'last_name'               => 'Brown',
    'date_of_birth'           => '1982-11-23',
    'gender'                  => 'male',
    'address'                 => '600 Cancer Center Dr',
    'city'                    => 'Philadelphia',
    'state'                   => 'PA',
    'zip_code'                => '19104',
    'email'                   => 'alexander.brown@hospital.com',
    'phone'                   => '+12340015',
    'emergency_contact_name'  => 'Jennifer Brown',
    'emergency_contact_phone' => '+12349985',
    'license_number'          => 'MD-PA-990011',
    'license_expiry_date'     => '2029-09-30',
    'qualifications'          => 'MD, PhD, Immunotherapy Training',
    'years_experience'        => 14,
    'education'               => 'University of Pennsylvania',
    'certifications'          => 'CAR-T Cell Therapy Certified',
    'position'                => 'Immuno-Oncologist',
    'hourly_rate'             => 460.00,
    'department_id'           => 5,
    'primary_specialization_id' => 10,     // Medical Oncology
    'profile_photo'           => null,
    'is_active'               => true,
],
        ];

        foreach ($doctors as $doctor) {
            Doctor::create($doctor);
        }

        Doctor::reguard();
    }
}