<?php

namespace Database\Seeders;

use App\Models\InventoryItem;
use App\Models\Category;
use App\Models\Supplier;
use App\Models\UnitOfMeasure;
use Illuminate\Database\Seeder;

class InventoryItemSeeder extends Seeder
{
    public function run(): void
    {
        InventoryItem::unguard();

        $items = [
            // Medicines
            [
                'name'                => 'Paracetamol 500mg Tablets',
                'sku'                 => 'PARA-500-TAB-100',
                'category_id'         => Category::where('name', 'Analgesics')->first()?->id,
                'primary_supplier_id' => Supplier::where('name', 'PharmaCare Distributors')->first()?->id,
                'generic_name'        => 'Paracetamol',
                'medicine_type'       => 'Tablet',
                'dosage'              => '500 mg',
                'unit_of_measure'     => 'Strip',
                'unit_quantity'       => 10,
                'unit_cost'           => 120.00,
                'unit_price'          => 180.00,
                'current_stock'       => 450,
                'minimum_stock_level' => 100,
                'reorder_point'       => 150,
                'reorder_quantity'    => 500,
                'expiry_tracking'     => true,
                'is_active'           => true,
            ],
            [
                'name'                => 'Amoxicillin 500mg Capsules',
                'sku'                 => 'AMOX-500-CAP-20',
                'category_id'         => Category::where('name', 'Antibiotics')->first()?->id,
                'primary_supplier_id' => Supplier::where('name', 'PharmaCare Distributors')->first()?->id,
                'generic_name'        => 'Amoxicillin',
                'medicine_type'       => 'Capsule',
                'dosage'              => '500 mg',
                'unit_of_measure'     => 'Box',
                'unit_quantity'       => 20,
                'unit_cost'           => 850.00,
                'unit_price'          => 1200.00,
                'current_stock'       => 120,
                'minimum_stock_level' => 30,
                'reorder_point'       => 50,
                'reorder_quantity'    => 200,
                'expiry_tracking'     => true,
                'is_active'           => true,
            ],
            [
                'name'                => 'Ceftriaxone 1g Injection',
                'sku'                 => 'CEFT-1G-VIAL',
                'category_id'         => Category::where('name', 'Antibiotics')->first()?->id,
                'primary_supplier_id' => Supplier::where('name', 'PharmaCare Distributors')->first()?->id,
                'generic_name'        => 'Ceftriaxone',
                'medicine_type'       => 'Injection',
                'dosage'              => '1 g',
                'unit_of_measure'     => 'Vial',
                'unit_quantity'       => 1,
                'unit_cost'           => 320.00,
                'unit_price'          => 480.00,
                'current_stock'       => 85,
                'minimum_stock_level' => 20,
                'reorder_point'       => 30,
                'reorder_quantity'    => 100,
                'expiry_tracking'     => true,
                'requires_refrigeration' => true,
                'is_active'           => true,
            ],
            [
                'name'                => 'Omeprazole 20mg Capsules',
                'sku'                 => 'OMEP-20-CAP-14',
                'category_id'         => Category::where('name', 'Pharmaceuticals')->first()?->id,
                'primary_supplier_id' => Supplier::where('name', 'PharmaCare Distributors')->first()?->id,
                'generic_name'        => 'Omeprazole',
                'medicine_type'       => 'Capsule',
                'dosage'              => '20 mg',
                'unit_of_measure'     => 'Strip',
                'unit_quantity'       => 14,
                'unit_cost'           => 210.00,
                'unit_price'          => 320.00,
                'current_stock'       => 320,
                'minimum_stock_level' => 80,
                'reorder_point'       => 120,
                'reorder_quantity'    => 400,
                'expiry_tracking'     => true,
                'is_active'           => true,
            ],
            [
                'name'                => 'Salbutamol 100mcg Inhaler',
                'sku'                 => 'SALB-100-INH',
                'category_id'         => Category::where('name', 'Pharmaceuticals')->first()?->id,
                'primary_supplier_id' => Supplier::where('name', 'PharmaCare Distributors')->first()?->id,
                'generic_name'        => 'Salbutamol',
                'medicine_type'       => 'Inhaler',
                'dosage'              => '100 mcg/dose',
                'unit_of_measure'     => 'Each',
                'unit_quantity'       => 1,
                'unit_cost'           => 1450.00,
                'unit_price'          => 1950.00,
                'current_stock'       => 65,
                'minimum_stock_level' => 15,
                'reorder_point'       => 25,
                'reorder_quantity'    => 100,
                'expiry_tracking'     => true,
                'is_active'           => true,
            ],

            // Non-medicine items
            [
                'name'                => 'Nitrile Examination Gloves (Large)',
                'sku'                 => 'NITR-L-GLOVE-100',
                'category_id'         => Category::where('name', 'Gloves')->first()?->id,
                'primary_supplier_id' => Supplier::where('name', 'Medico Supplies Ltd.')->first()?->id,
                'unit_of_measure'     => 'Box',
                'unit_quantity'       => 100,
                'unit_cost'           => 1850.00,
                'unit_price'          => 2400.00,
                'current_stock'       => 280,
                'minimum_stock_level' => 50,
                'reorder_point'       => 80,
                'reorder_quantity'    => 300,
                'is_active'           => true,
            ],
            [
                'name'                => '3-Ply Surgical Face Masks',
                'sku'                 => 'MASK-3PLY-50',
                'category_id'         => Category::where('name', 'Masks')->first()?->id,
                'primary_supplier_id' => Supplier::where('name', 'Medico Supplies Ltd.')->first()?->id,
                'unit_of_measure'     => 'Box',
                'unit_quantity'       => 50,
                'unit_cost'           => 650.00,
                'unit_price'          => 950.00,
                'current_stock'       => 1200,
                'minimum_stock_level' => 200,
                'reorder_point'       => 300,
                'reorder_quantity'    => 1000,
                'is_active'           => true,
            ],
            [
                'name'                => 'Digital Blood Pressure Monitor',
                'sku'                 => 'BP-MONITOR-DIGI',
                'category_id'         => Category::where('name', 'Blood Pressure Monitors')->first()?->id,
                'primary_supplier_id' => Supplier::where('name', 'HealthTech Solutions')->first()?->id,
                'unit_of_measure'     => 'Each',
                'unit_quantity'       => 1,
                'unit_cost'           => 4800.00,
                'unit_price'          => 6500.00,
                'current_stock'       => 38,
                'minimum_stock_level' => 10,
                'reorder_point'       => 15,
                'reorder_quantity'    => 50,
                'is_active'           => true,
            ],
            [
                'name'                => 'Sterile Gauze Swabs 10x10cm',
                'sku'                 => 'GAUZE-10X10-100',
                'category_id'         => Category::where('name', 'Gauze Pads')->first()?->id,
                'primary_supplier_id' => Supplier::where('name', 'Medico Supplies Ltd.')->first()?->id,
                'unit_of_measure'     => 'Pack',
                'unit_quantity'       => 100,
                'unit_cost'           => 950.00,
                'unit_price'          => 1350.00,
                'current_stock'       => 420,
                'minimum_stock_level' => 80,
                'reorder_point'       => 120,
                'reorder_quantity'    => 500,
                'sterile'             => true,
                'is_active'           => true,
            ],
            [
                'name'                => 'Disposable Syringes 5ml',
                'sku'                 => 'SYR-5ML-100',
                'category_id'         => Category::where('name', 'Syringes & Needles')->first()?->id,
                'primary_supplier_id' => Supplier::where('name', 'Medico Supplies Ltd.')->first()?->id,
                'unit_of_measure'     => 'Box',
                'unit_quantity'       => 100,
                'unit_cost'           => 1100.00,
                'unit_price'          => 1600.00,
                'current_stock'       => 750,
                'minimum_stock_level' => 150,
                'reorder_point'       => 250,
                'reorder_quantity'    => 1000,
                'sterile'             => true,
                'is_active'           => true,
            ],
        ];

        foreach ($items as $item) {
            InventoryItem::create($item);
        }

        InventoryItem::reguard();
    }
}